sms:
  content:
    car-approach: 司机{0}:您好,请您于时间:{1}进入{2}园区进行装卸货,垛口:{3}

    person-account: 访客{0}:您好,您的智慧园区小程序登录账号为:{1},密码为:{2},请登录后进行后续操作

    person-card-check: 访客{0}:您好,您已通过园区人证校验,请进入园区!

    visitor-appt-appoint: 访客申请人{0}:您好,您申请的访客预约{1}

    order-pass: 您在{2}园区{3}时间预约成功,请在指定时间内驾驶车辆{1}到达园区。温馨提示：请您入园前在小程序上完成入园学习并通过入园考核，预约当日携带身份证通过核验后入园，谢谢!

    order-update: 司机{0}:您好,您在{2}园区预约的{1}车辆的预约任务有临时调整,{3}请及时登录到小程序上查看！

    order-cancel: 您在{2}园区预约的{1}车辆{3}的预约任务已被取消如有疑问请联系仓库调度员！

    order-lated-driver: 您在{2}园区预约的{1}车辆{3}的预约任务因迟到超过30分钟已被取消,如有疑问请联系仓库调度员！

    order-lated-carrier: 园区{0}预约的{1}车辆{2}的预约任务因迟到超过30分钟已被取消,如有疑问请联系仓库调度员！

    order-lated-staff: 承运商{0}预约的{1}车辆{2}的预约任务因迟到超过30分钟已被取消,请联系承运商调度或司机了解情况！

    car-retention-staff: 园区内的{0}车辆滞留报警，请及时去了解情况！

    car-retention-carrier: 园区{0}预约的{1}车辆滞留报警，请联系司机尽快出园！

    #车辆入侵
    "10": 车牌[{0}],在时间[{1}],开闸失败,请检查车辆是否在预约时间段内,且已经授权入园,设备名称[{3}]

    #人员入侵
    "11": 身份证号[{0}],在时间[{1}],开闸失败,请检查人员是否在白名单内或者在预约时间段内,且已完成人证合一检测,设备名称[{2}]

    #车辆滞留
    "20": 预约单[{0}]车辆[{1}]已滞留[{2}]分钟,预约离场时间为[{3}],请通知司机尽快离场

    #消防报警
    "21": 「消防报警」{0},设备名称【{1}】,安装地点【{2}】！
