server:
  port: 8080
spring:
  # 默认 dev 环境
  profiles:
    active: test
  # 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.43.111:3306/my_db
    username: root
    password: 123456
  redis:
    host: 139.9.228.247
    port: 6378
    password: yiwei2023



# spring-doc 接口文档
springdoc:
  api-docs:
    enabled: true # 是否启用接口文档
    springdoc:
      # 默认是false，需要设置为true
      default-flat-param-object: true
knife4j:
  # 开启增强配置
  enable: true # 开启Swagger的Basic认证功能,默认是false
  basic:
    enable: true
    # Basic认证用户名
    username: admin
    # Basic认证密码
    password: 112233



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0

