# 在Eureka web修改实例显示名称
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true # 按主机名默认访问方法，我们通常要配置true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
